⬆️ Bump files with dotnet-file sync ﻿# devlooped/oss
- feat: add validation step to check for disallowed package versions in publish workflow https://github.com/devlooped/oss/commit/0ca5fd1
- Update cron schedule in triage workflow https://github.com/devlooped/oss/commit/5ee8c91

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,7 +10,9 @@ on:
 env:
   DOTNET_NOLOGO: true
   Configuration: Release
-  VersionLabel: ${{ github.ref }}
+  PackOnBuild: true
+  GeneratePackageOnBuild: true
+  VersionLabel: refs/tags/${{ github.event.release.tag_name }}
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
   MSBUILDTERMINALLOGGER: auto
   SLEET_FEED_URL: https://api.nuget.org/v3/index.json
@@ -32,16 +34,8 @@ jobs:
         run: dotnet build -m:1 -bl:build.binlog
 
       - name: 🧪 test
-        run: dnx --yes retest -- --no-build
-
-      - name: 🙏 publish
         shell: pwsh
-        run: |
-          $rids = dotnet msbuild src/go/go.csproj -getproperty:RuntimeIdentifiers 
-          $rids | %{ $_.Split(';') } | %{ $_.Trim() } | ? { $_ } | %{ dotnet publish src/go/go.csproj -r $_ }
-
-      - name: 📦 pack
-        run: dotnet pack src/go/go.csproj --no-build -m:1 -bl:pack.binlog
+        run: dnx --yes retest -- --no-build
 
       - name: 🐛 logs
         uses: actions/upload-artifact@v4
@@ -49,6 +43,16 @@ jobs:
         with:
           name: logs
           path: '*.binlog'
+
+      - name: ✅ validate
+        shell: pwsh
+        working-directory: bin
+        run: |
+          $invalid = Get-ChildItem -File -Filter "*.42.42*.nupkg"
+          if ($invalid) {
+            Write-Error "Found dev/local packages with disallowed 42.42* version prefix:`n$($invalid.Name -join "`n")"
+            exit 1
+          }
 
       - name: 🚀 nuget
         env:
